name: 'LA build'
description: 'Build the LA lib or app'
inputs:
  push_bindings:
    description: "Whether to (build and) push the csharp bindings"
    default: 'false'
  GTEST_FILTER:
    description: "The filter to be applied to gtest execution."
    default: "-INTEGRATION*"
  SWIG_EXEC:
    description: "The swig executable path"
  SWIG_DIR:
    description: "The swig directory path"
  BUILD_DIR:
    description: "The build directory."
    default: "_build"
  MACOS_SIGNING_IDENTITY:
    description: "The signing identity to use if no default is provided."
    default: "-"
  include_nuget_la_feed_url:
    description:  "Whether to include the L-Acoustics nuget feed url as source, required if pushing to a different feed than L-Acoustics one"
    default: 'false'
  CONFIG:
    description: "The build configuration, debug or release"
  NUGET_PUBLISH_FEED_URL:
    description:  "The nuget feed url to pushed the package to"
  LIB_NAME:
    description: "The library or app name"
  NUGET_LA_FEED_URL:
    description: "The L-Acoustics nuget feed url"
    default: https://nuget.pkg.github.com/L-Acoustics/index.json
  RUNNER_ARCH:
    description: "The output requested architecture"
    default: "x64"
  GITHUB_TOKEN:
    description: "The github token used to push package"

runs:
  using: composite
  steps:
    - name: Check support
      shell: bash
      run: |
        supported_os=("Linux" "Windows" "macOS")
        input_os=${{runner.os}}
        if [[ ! " ${supported_os[@]} " =~ " $input_os " ]]; then
          echo "Error: Un-supported OS ${{runner.os}}. Supported os values: ${supported_os[*]}."
          exit 1
        fi
        echo "Running on platform [$input_os]"

    - name: Set environment variables
      shell: bash
      run: |
        echo "RUNNER_OS=${{runner.os}}" >> $GITHUB_ENV
        echo "RUNNER_ARCH=${{inputs.RUNNER_ARCH}}" >> $GITHUB_ENV
        echo "NUGET_PUBLISH_FEED_URL=${{inputs.NUGET_PUBLISH_FEED_URL}}" >> $GITHUB_ENV
        echo "NUGET_LA_FEED_URL=${{inputs.NUGET_LA_FEED_URL}}" >> $GITHUB_ENV
        echo "LIB_NAME=${{inputs.LIB_NAME}}" >> $GITHUB_ENV
        echo "GITHUB_TOKEN=${{inputs.GITHUB_TOKEN}}" >> $GITHUB_ENV
        echo "BUILD_DIRECTORY=${{inputs.BUILD_DIR}}_${{inputs.RUNNER_ARCH}}" >> $GITHUB_ENV

    - name: Generate Cmake
      shell: bash
      run: |
        echo "Generating CMake for Configuration : ${{inputs.CONFIG}}"
        dotnet nuget add source --username "${{github.repository_owner}}" --password ${{env.GITHUB_TOKEN}} --store-password-in-clear-text --name current_feed "${{env.NUGET_PUBLISH_FEED_URL}}"
        if [ ${{inputs.include_nuget_la_feed_url}} = 'true' ];then
          dotnet nuget add source --username "${{github.repository_owner}}" --password ${{env.GITHUB_TOKEN}} --store-password-in-clear-text --name la_feed "${{env.NUGET_LA_FEED_URL}}"
        fi

        if [[ ${{env.RUNNER_ARCH}} == "universal" ]];then
        ./gen_cmake.sh -o ${{env.BUILD_DIRECTORY}} -${{inputs.CONFIG}} -c Ninja -build-csharp -all-archs -- \
          "-DNUGET_PUBLISH_SOURCE_URL=${{env.NUGET_PUBLISH_FEED_URL}}" \
          "-DNUGET_PUBLISH_API_KEY=${{env.GITHUB_TOKEN}}" \
          "-DSWIG_DIR=${{inputs.SWIG_DIR}}" \
          "-DCU_REPO_URL=https://github.com/${{github.repository}}" \
          "-DSWIG_EXECUTABLE=${{inputs.SWIG_EXEC}}" \
          "-DBUILD_ATDECC_AUTOMATION_EXAMPLES=FALSE"
        else
        ./gen_cmake.sh -o ${{env.BUILD_DIRECTORY}} -${{inputs.CONFIG}} -c Ninja -build-csharp -arch ${{env.RUNNER_ARCH}} -- \
        "-DNUGET_PUBLISH_SOURCE_URL=${{env.NUGET_PUBLISH_FEED_URL}}" \
        "-DNUGET_PUBLISH_API_KEY=${{env.GITHUB_TOKEN}}" \
        "-DSWIG_DIR=${{inputs.SWIG_DIR}}" \
        "-DCU_REPO_URL=https://github.com/${{github.repository}}" \
        "-DSWIG_EXECUTABLE=${{inputs.SWIG_EXEC}}" \
        "-DBUILD_ATDECC_AUTOMATION_EXAMPLES=FALSE"
        fi

    - name: Build
      shell: bash
      run: |
        cmake --build ${{env.BUILD_DIRECTORY}} --target Tests

    - name: Test
      shell: bash
      run: |
        cd ${{env.BUILD_DIRECTORY}}/tests/src
        test_cmd="./Tests --gtest_filter=${{inputs.GTEST_FILTER}}"
        if [ "${{matrix.config}}" = "debug" ]; then
          test_cmd="./Tests-d --gtest_filter=${{inputs.GTEST_FILTER}}"
        fi
        eval $test_cmd

    - name: Build all
      shell: bash
      run: |
        cmake --build ${{env.BUILD_DIRECTORY}}

    - name: Push bindings
      if: inputs.push_bindings == 'true'
      shell: bash
      run: |
        cmake --build ${{env.BUILD_DIRECTORY}} --target ${{env.LIB_NAME}}-csharp-nuget-push

