name: 'LA build'
description: 'Build the LA app'
inputs:
  KEYCHAIN_PASSWORD:
    description: "The keychain password holding the certificates for signing."
  GTEST_FILTER:
    description: "The filter to be applied to gtest execution."
    default: "-INTEGRATION*"
  BUILD_DIR:
    description: "The build directory."
    default: "_build"
  MACOS_SIGNING_IDENTITY:
    description: "The signing identity to use if no default is provided."
    default: "-"
  CONFIG:
    description: "The build configuration, debug or release"
  APP_NAME:
    description: "The library or app name"
  RUNNER_ARCH:
    description: "The output requested architecture"
    default: "x64"
  GITHUB_TOKEN:
    description: "The github token used to push package"

runs:
  using: composite
  steps:
    - name: Check support
      shell: bash
      run: |
        supported_os=("Windows" "macOS")
        input_os=${{runner.os}}
        if [[ ! " ${supported_os[@]} " =~ " $input_os " ]]; then
          echo "Error: Un-supported OS ${{runner.os}}. Supported os values: ${supported_os[*]}."
          exit 1
        fi
        echo "Running on platform [$input_os]"

    - name: Set environment variables
      shell: bash
      run: |
        echo "RUNNER_OS=${{runner.os}}" >> $GITHUB_ENV
        echo "RUNNER_ARCH=${{inputs.RUNNER_ARCH}}" >> $GITHUB_ENV
        echo "APP_NAME=${{inputs.APP_NAME}}" >> $GITHUB_ENV
        echo "GITHUB_TOKEN=${{inputs.GITHUB_TOKEN}}" >> $GITHUB_ENV
        echo "BUILD_DIRECTORY=${{inputs.BUILD_DIR}}_${{inputs.RUNNER_ARCH}}" >> $GITHUB_ENV

    - name: Prepare project
      shell: bash
      run: |
        echo "create .config"
        echo "Setting notarization profile."
        sed 's/.*notarization_profile.*/notarization_profile=lacoustics/' .config.sample > .config

        echo "create .default.sh"
        cp .defaults.sh.sample .defaults.sh

        echo "Call setup_fresh_env.sh"
        ./setup_fresh_env.sh

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.10.2'
        setup-python: false
        cache: true

    - name: Build app
      shell: bash
      run: |
        KEYCHAIN_PASSWORD=${{inputs.KEYCHAIN_PASSWORD}}
        security unlock-keychain -p "$KEYCHAIN_PASSWORD"

        echo "Building for config: ${{inputs.CONFIG}}"
        qtdir="$QT_ROOT_DIR/lib/cmake"
        ./gen_install.sh -c Ninja -qtdir $qtdir -qtvers 6.10.2

    - name: Build artifacts
      if: runner.os == 'macOS'
      uses: actions/upload-artifact@v4
      with:
        name: macos_build_artifacts
        path: _deliverables/*.*
        retention-days: 5
