name: 'Configure LA Runner'
description: 'Configure the runner to build LA lib/app'
inputs:
  KEYCHAIN_PASSWORD:
    description:  'The keychain password to use'
  APPLE_CERTIFICATES_P12_BASE64_PASSWORD:
    description: 'The app certificate password'
  APPLE_CERTIFICATES_P12_BASE64:
    description: 'The base64 encoded certificate for app signing'
  WINPCAP_ROOT_DESTINATION:
    description: 'The root folder into which winpcap will be installed e.g. $root/externals/3rdparty/winpcap default is the current folder'
    default: "."
  setup_keychain:
    description: 'Should setup the keychain certificate for macos code signing.'
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Check support
      shell: bash
      run: |
        supported_os=("Linux" "Windows" "macOS")
        input_os=${{runner.os}}
        if [[ ! " ${supported_os[@]} " =~ " $input_os " ]]; then
          echo "Error: Un-supported OS ${{inputs.os}}. Supported os values: ${supported_os[*]}."
          exit 1
        fi
        echo "Running on platform [$input_os]"

    - name: Set environment variables
      shell: bash
      run: |
        echo "SWIG_BRANCH=aggregated_release" >> $GITHUB_ENV
        echo "SWIG_REPOSITORY=https://github.com/christophe-calmejane/swig.git" >> $GITHUB_ENV
        echo "RUNNER_OS=${{runner.os}}" >> $GITHUB_ENV
        echo "RUNNER_ARCH=${{runner.arch}}" >> $GITHUB_ENV

    # ----------------- Linux -----------------
    - name: Install dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y wget ninja-build build-essential libpcap-dev

    - name: Install CMake
      if: runner.os == 'Linux'
      shell: bash
      run: |
        set +xe
        which cmake &> /dev/null
        if [ $? -ne 0 ]; then
          arch=$([ $(uname -m) = "arm64" ] && echo "aarch64" || echo "x86_64")
          cmake_script="cmake-3.31.5-linux-$arch.sh"
          wget "https://github.com/Kitware/CMake/releases/download/v3.31.5/$cmake_script"
          chmod +x $cmake_script
          sudo ./$cmake_script --skip-license --prefix=/usr/local
        fi
        CMAKE_VERSION=$(cmake --version | awk '/version/ {print $3}')
        echo "USING CMAKE: ${CMAKE_VERSION}"

    # ----------------- Windows -----------------
    - name: Install job dependencies
      if: runner.os == 'Windows'
      shell: bash
      run: |
        choco install -y grep
        CMAKE_VERSION=$(cmake --version | awk '/version/ {print $3}')
        echo "USING CMAKE: ${CMAKE_VERSION}"

    - name: Install winpcap
      if: runner.os == 'Windows'
      shell: bash
      run: |
        wpdpack_zip_name="WpdPack_4_1_2.zip"
        winpcap_url="https://www.winpcap.org/install/bin/$wpdpack_zip_name"
        winpcap_ext_dir="${{inputs.WINPCAP_ROOT_DESTINATION}}/externals/3rdparty/winpcap"
        if [ ! -d $winpcap_ext_dir ]; then
          mkdir --parent $winpcap_ext_dir
        fi
        curl -O $winpcap_url
        unzip $wpdpack_zip_name -d _winpcap
        mv _winpcap/WpdPack/Include $winpcap_ext_dir/Include
        mv _winpcap/WpdPack/Lib $winpcap_ext_dir/Lib

    - name: Configure compiler and generator cli
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    # ----------------- macOS -----------------
    - name: Install job dependencies
      if: runner.os == 'macOS'
      shell: bash
      run : |
        brew install ninja
        brew install wget
        brew install bash
        brew install grep
        echo "$(brew --prefix grep)/libexec/gnubin" >> $GITHUB_PATH

    - name: Install CMake
      if: runner.os == 'macOS'
      shell: bash
      run : |
        set -xe # exit on first error
        which cmake &> /dev/null
        CMAKE_VERSION=$(cmake --version | awk '/version/ {print $3}')
        echo "USING CMAKE: ${CMAKE_VERSION}"

    - name: Setup keychain
      if: runner.os == 'macOS' && inputs.setup_keychain == 'true'
      shell: bash
      run: |
        KEYCHAIN_PASSWORD="${{inputs.KEYCHAIN_PASSWORD}}"
        APPLE_CERTIFICATES_P12_BASE64="${{inputs.APPLE_CERTIFICATES_P12_BASE64}}"
        APPLE_CERTIFICATES_P12_BASE64_PASSWORD="${{inputs.APPLE_CERTIFICATES_P12_BASE64_PASSWORD}}"
        echo "Setting up keychain"
        security create-keychain -p "$KEYCHAIN_PASSWORD" action.keychain
        security default-keychain -s action.keychain
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" action.keychain
        echo "$APPLE_CERTIFICATES_P12_BASE64" | base64 --decode > certificate_app.p12
        security import certificate_app.p12 -k action.keychain -P "$APPLE_CERTIFICATES_P12_BASE64_PASSWORD" -T /usr/bin/productsign -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple:,codesign:,productsign: -s -k "$KEYCHAIN_PASSWORD" action.keychain
        echo "Printing available identities:"
        security find-identity -v
